name: Publish to npm

on:
  push:
    branches: [ "release" ]

jobs:
  publish:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        always-auth: true

 
      
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
